name: Refresh bibliography
on: [push, workflow_dispatch]
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://api.zotero.org/groups/1553639/items?format=json&sort=date
          configuration: '{ "method": "GET"}'
      - name: Build and Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # Pushes the updates to the main branch.
          folder: fetch-api-data-action # The location of the data.json file saved by the Fetch API Data action.
          target-folder: data # Saves the data into the 'data' directory on the main branch.
